window.setTimeout(() => alert('HAMMERTIME'), 5000);
// ...
// ...
// ...
// ...
// ...
// 'HAMMERTIME'

// With a closure
function hammerTime(time) {
  window.setTimeout(() => alert(`${time} is hammertime!`), 5000);
}
hammerTime('12:00');
// ...
// ...
// ...
// ...
// ...
// '12:00 is hammertime!'
