# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 00e788a30e5a875f29f40b0da61547c48aa397cda4876eaafbeeb46beaf957dcd3e51164c47b0d966eb7114074ff69764cd6ff949094f67feacd7b67f8fe61a3

test:
  secret_key_base: b38df17e5f1ca335cb51988d44db0873708cbf047ee035752e14a31b77924451014ec37ccb65c928621ed6b87154cf9fe08beb92bb4ca396b7379932dc07ec33

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
