# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6484e21287b4d035cf5184faaa2d33fbab2a6733af4211cc1b9aac4801f8e82ae05adb5f8815af8be6dfdea1aa7b8fb8a33632bb645d7933f0a116f712b0844f

test:
  secret_key_base: 795725640e6ee1de0d3640395f77c3979eaff2746a2a76924a406240128541c22a086ee6f912490ca8b0e7ee40da31ee511a08764b762a817a3dcdf0912efc02

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
